<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="10" ignored="0" total="10" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="RegressionPack" duration-ms="3635" started-at="2019-02-09T18:31:10Z" finished-at="2019-02-09T18:31:14Z">
    <groups>
      <group name="API_Method">
        <method signature="EdrFlow1.API_Method(com.edr.models.TestDataOneModel)[pri:0, instance:com.edr.businesscomponents.EdrFlow1@57f23557]" name="API_Method" class="com.edr.businesscomponents.EdrFlow1"/>
      </group> <!-- API_Method -->
    </groups>
    <test name="Exception_1" duration-ms="3635" started-at="2019-02-09T18:31:10Z" finished-at="2019-02-09T18:31:14Z">
      <class name="com.edr.businesscomponents.EdrFlow1">
        <test-method status="PASS" signature="init()[pri:0, instance:com.edr.businesscomponents.EdrFlow1@57f23557]" name="init" is-config="true" duration-ms="740" started-at="2019-02-09T18:31:10Z" finished-at="2019-02-09T18:31:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="setUpTest()[pri:0, instance:com.edr.businesscomponents.EdrFlow1@57f23557]" name="setUpTest" is-config="true" duration-ms="3522" started-at="2019-02-09T18:31:10Z" finished-at="2019-02-09T18:31:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.edr.businesscomponents.EdrFlow1@57f23557]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-02-09T18:31:14Z" finished-at="2019-02-09T18:31:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.edr.businesscomponents.EdrFlow1@57f23557]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-02-09T18:31:14Z" finished-at="2019-02-09T18:31:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="API_Method(com.edr.models.TestDataOneModel)[pri:0, instance:com.edr.businesscomponents.EdrFlow1@57f23557]" name="API_Method" duration-ms="16" started-at="2019-02-09T18:31:14Z" data-provider="dataProvider" finished-at="2019-02-09T18:31:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.edr.models.TestDataOneModel@1e2dd0a8]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.edr.businesscomponents.EdrFlow1.getCRN(EdrFlow1.java:59)
at com.edr.businesscomponents.EdrFlow1.API_Method(EdrFlow1.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_Method -->
        <test-method status="FAIL" signature="API_Method(com.edr.models.TestDataOneModel)[pri:0, instance:com.edr.businesscomponents.EdrFlow1@57f23557]" name="API_Method" duration-ms="16" started-at="2019-02-09T18:31:14Z" data-provider="dataProvider" finished-at="2019-02-09T18:31:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.edr.models.TestDataOneModel@72d8a18a]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.edr.businesscomponents.EdrFlow1.getCRN(EdrFlow1.java:59)
at com.edr.businesscomponents.EdrFlow1.API_Method(EdrFlow1.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_Method -->
        <test-method status="FAIL" signature="API_Method(com.edr.models.TestDataOneModel)[pri:0, instance:com.edr.businesscomponents.EdrFlow1@57f23557]" name="API_Method" duration-ms="51" started-at="2019-02-09T18:31:14Z" data-provider="dataProvider" finished-at="2019-02-09T18:31:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.edr.models.TestDataOneModel@475c07a4]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.edr.businesscomponents.EdrFlow1.getCRN(EdrFlow1.java:59)
at com.edr.businesscomponents.EdrFlow1.API_Method(EdrFlow1.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_Method -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.edr.businesscomponents.EdrFlow1@57f23557]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2019-02-09T18:31:14Z" finished-at="2019-02-09T18:31:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.edr.businesscomponents.EdrFlow1@57f23557]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-02-09T18:31:14Z" finished-at="2019-02-09T18:31:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.edr.businesscomponents.EdrFlow1@57f23557]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-02-09T18:31:14Z" finished-at="2019-02-09T18:31:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="API_Method(com.edr.models.TestDataOneModel)[pri:0, instance:com.edr.businesscomponents.EdrFlow1@57f23557]" name="API_Method" duration-ms="49" started-at="2019-02-09T18:31:14Z" data-provider="dataProvider" finished-at="2019-02-09T18:31:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.edr.models.TestDataOneModel@510850b]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.edr.businesscomponents.EdrFlow1.getCRN(EdrFlow1.java:59)
at com.edr.businesscomponents.EdrFlow1.API_Method(EdrFlow1.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_Method -->
        <test-method status="FAIL" signature="API_Method(com.edr.models.TestDataOneModel)[pri:0, instance:com.edr.businesscomponents.EdrFlow1@57f23557]" name="API_Method" duration-ms="33" started-at="2019-02-09T18:31:14Z" data-provider="dataProvider" finished-at="2019-02-09T18:31:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.edr.models.TestDataOneModel@7a52a6cc]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.edr.businesscomponents.EdrFlow1.getCRN(EdrFlow1.java:59)
at com.edr.businesscomponents.EdrFlow1.API_Method(EdrFlow1.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_Method -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.edr.businesscomponents.EdrFlow1@57f23557]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-02-09T18:31:14Z" finished-at="2019-02-09T18:31:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.edr.businesscomponents.EdrFlow1@57f23557]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2019-02-09T18:31:14Z" finished-at="2019-02-09T18:31:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="API_Method(com.edr.models.TestDataOneModel)[pri:0, instance:com.edr.businesscomponents.EdrFlow1@57f23557]" name="API_Method" duration-ms="56" started-at="2019-02-09T18:31:14Z" data-provider="dataProvider" finished-at="2019-02-09T18:31:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.edr.models.TestDataOneModel@343e042d]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.edr.businesscomponents.EdrFlow1.getCRN(EdrFlow1.java:59)
at com.edr.businesscomponents.EdrFlow1.API_Method(EdrFlow1.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_Method -->
        <test-method status="FAIL" signature="API_Method(com.edr.models.TestDataOneModel)[pri:0, instance:com.edr.businesscomponents.EdrFlow1@57f23557]" name="API_Method" duration-ms="54" started-at="2019-02-09T18:31:14Z" data-provider="dataProvider" finished-at="2019-02-09T18:31:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.edr.models.TestDataOneModel@443a76ed]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.edr.businesscomponents.EdrFlow1.getCRN(EdrFlow1.java:59)
at com.edr.businesscomponents.EdrFlow1.API_Method(EdrFlow1.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_Method -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.edr.businesscomponents.EdrFlow1@57f23557]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-02-09T18:31:14Z" finished-at="2019-02-09T18:31:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.edr.businesscomponents.EdrFlow1@57f23557]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-02-09T18:31:14Z" finished-at="2019-02-09T18:31:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.edr.businesscomponents.EdrFlow1@57f23557]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2019-02-09T18:31:14Z" finished-at="2019-02-09T18:31:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="API_Method(com.edr.models.TestDataOneModel)[pri:0, instance:com.edr.businesscomponents.EdrFlow1@57f23557]" name="API_Method" duration-ms="13" started-at="2019-02-09T18:31:14Z" data-provider="dataProvider" finished-at="2019-02-09T18:31:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.edr.models.TestDataOneModel@251e2912]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.edr.businesscomponents.EdrFlow1.getCRN(EdrFlow1.java:59)
at com.edr.businesscomponents.EdrFlow1.API_Method(EdrFlow1.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_Method -->
        <test-method status="FAIL" signature="API_Method(com.edr.models.TestDataOneModel)[pri:0, instance:com.edr.businesscomponents.EdrFlow1@57f23557]" name="API_Method" duration-ms="11" started-at="2019-02-09T18:31:14Z" data-provider="dataProvider" finished-at="2019-02-09T18:31:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.edr.models.TestDataOneModel@2d50c86f]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.edr.businesscomponents.EdrFlow1.getCRN(EdrFlow1.java:59)
at com.edr.businesscomponents.EdrFlow1.API_Method(EdrFlow1.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_Method -->
        <test-method status="FAIL" signature="API_Method(com.edr.models.TestDataOneModel)[pri:0, instance:com.edr.businesscomponents.EdrFlow1@57f23557]" name="API_Method" duration-ms="11" started-at="2019-02-09T18:31:14Z" data-provider="dataProvider" finished-at="2019-02-09T18:31:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.edr.models.TestDataOneModel@435413d5]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.edr.businesscomponents.EdrFlow1.getCRN(EdrFlow1.java:59)
at com.edr.businesscomponents.EdrFlow1.API_Method(EdrFlow1.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- API_Method -->
        <test-method status="PASS" signature="terminate()[pri:0, instance:com.edr.businesscomponents.EdrFlow1@57f23557]" name="terminate" is-config="true" duration-ms="0" started-at="2019-02-09T18:31:14Z" finished-at="2019-02-09T18:31:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- terminate -->
        <test-method status="FAIL" signature="tearDown()[pri:0, instance:com.edr.businesscomponents.EdrFlow1@57f23557]" name="tearDown" is-config="true" duration-ms="0" started-at="2019-02-09T18:31:14Z" finished-at="2019-02-09T18:31:14Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.edr.businesscomponents.BaseClass.tearDown(BaseClass.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.afterRun(TestRunner.java:725)
at org.testng.TestRunner.run(TestRunner.java:509)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.edr.businesscomponents.EdrFlow1 -->
    </test> <!-- Exception_1 -->
  </suite> <!-- RegressionPack -->
</testng-results>
